nota1= float(input("Informe a primeira nota do aluno: "))
nota2= float(input("Informe a segunda nota do aluno: "))
nota3= float(input("Informe a terceira nota do aluno: "))
final=(nota1*0.3) + (nota2*0.2) + (nota3*0.5)
print("A nota final é: ", final)
